spring:
  application:
    name: cloud-pro-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_pro?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 491001
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans
swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.cloud.pro
  title: cloud-pro docs
  description: cloud-pro docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: han
  contact-url: han
  contact-email: 1138841120@qq.com
  version: 1.0