spring:
  application:
    name: cloud-pro-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans