server:
  port: 8090
spring:
  application:
    name: cloud-pro-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_pro?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 491001
  # Redis 配置
  redis:
    database: 0
    host: 192.168.5.100
    #    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password: 491001
    lettuce: #lettuce是springboot内置的，如果用jedis还需要导入相应依赖
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 1000ms #连接等待时间
  # rocketMQ配置
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        testInput:
          destination: testTopic # 消费topic
          group: testGroup1 # 消费组
        testOutput:
          destination: testTopic
        errorLogInput:
          destination: errorLogTopic
          group: errorLogGroup
        deleteFileInput:
            destination: deleteFileTopic
            group: deleteFileGroup
        fileRestoreInput:
            destination: fileRestoreTopic
            group: fileRestoreGroup
        physicalDeleteFileInput:
            destination: physicalDeleteFileTopic
            group: physicalDeleteFileGroup
        userSearchInput:
            destination: userSearchTopic
            group: userSearchGroup
        errorLogOutput:
            destination: errorLogTopic
        deleteFileOutput:
            destination: deleteFileTopic
        fileRestoreOutput:
            destination: fileRestoreTopic
        physicalDeleteFileOutput:
            destination: physicalDeleteFileTopic
        userSearchOutput:
            destination: userSearchTopic
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans
swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.cloud.pro
  title: cloud-pro docs
  description: cloud-pro docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: han
  contact-url: han
  contact-email: 1138841120@qq.com
  version: 1.0
com:
  cloud:
    pro:
      storage:
        engine:
#          fdfs:
#            connect-timeout: 1000
#            tracker-list:
#              - localhost:22122
#            group: group1
          oss:
            endpoint: oss-cn-shanghai.aliyuncs.com
            access-key-id:
            access-key-secret:
            bucket-name: cloud-pro-test
            auto-create-bucket: true
      server:
        # 分享链接前缀，前端地址
        share-prefix: http://127.0.0.1:5173/
      bloom:
        filter:
          local:
            items:
              - name: SHARE_SIMPLE_DETAIL
                funnel-type-name: LONG
                expected-insertions: 1000_0000
                fpp: 0.01